### ISSUE TITLE
trigBoard  V8 schematic

### ISSUE THREAD

**Issue by zpm1066** [krdarrah/trigBoardV8_BaseFirmware#4]
Is the trigBoard schematic pdf available?

What LDO regulator is on the triBoard V8?   Thanks.

**Comment by zpm1066** [comment]
What is the maximum output current & quiescent current of the trigBoard V8? Thanks.

**Comment by krdarrah** [comment]
Have you seen this:  https://trigboard-docs.readthedocs.io/en/latest/Hardware.html <https://trigboard-docs.readthedocs.io/en/latest/Hardware.html>

But you can expect ~1uA or so typical of sleep current, and the output I’m assuming is for the 3.3V?  That is used internally by the ESP32, but can also be used to power sensors, etc… I would limit this to <100mA

Best Regards,
Kevin Darrah
***@***.***

**Comment by zpm1066** [comment]
Excellent Kevin. You have superb online documentation. I’ll review it more, though I have not found a schematic yet. Do you have the schematic available to share?  Thanks.

**Comment by krdarrah** [comment]
Thanks! But sorry, schematic is not fully released yet

Best Regards,
Kevin Darrah
***@***.***

**Comment by zpm1066** [comment]
Hi Kevin,
Thanks for responding. No problem regarding the trigBoard V8 schematic. The detail and clarity of your online documentation  is fantastic! Thank you for sharing the material.
